# Generated by Django 6.0.6 on 2026-06-06 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_userloginlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('changed_fields', models.JSONField(verbose_name='变更字段列表')),
                ('old_values', models.JSONField(verbose_name='修改前的值')),
                ('new_values', models.JSONField(verbose_name='修改后的值')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_changes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人信息修改记录',
                'verbose_name_plural': '个人信息修改记录',
                'db_table': 'user_profile_change_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_user_profile_change')],
            },
        ),
    ]
