# Generated by Django 4.x on 2025-06-01
import uuid
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('analysis_config', models.JSONField(default=dict, verbose_name='分析配置')),
                ('result_data', models.JSONField(default=dict, verbose_name='分析结果')),
                ('summary_stats', models.JSONField(default=dict, verbose_name='统计摘要')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'db_table': 'analysis_results',
                'verbose_name': '分析结果',
                'verbose_name_plural': '分析结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
